---
title: "argos-blvu - 4. data analysis BLVU AGL analysis "
author: "Adam Duerr"
date: "`r Sys.Date()`"
output: html_document
---

notes: try to use all lowercase for files just to simplify typing and retyping the names
use git and renv to track changes to the project
git repo is https:/github.com/adamdaz/argos-blvu/

add info to each chunk to track whether it was run recently and how long it took
```{r}
# tic()
# 
# cat("
# Ran at: ");Sys.time()
# toc()
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


libraries
```{r}
library(usethis) #git stuff
library(renv) #versioning tools
library(tictoc) #tracking time
library(data.table) #allows multi-core processing for reading/writing tables = fast!
library(lme4)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ResourceSelection)
library(MuMIn)
```


read the data for analysis 
```{r}
tic()

blvu1<- fread("blvu1.csv")

colnames(blvu1)

cat("
Ran at: ");Sys.time()
toc()
```


Analysis of data for BLVU AGL

```{r}
tic()

glmm1 <- lmer (agl ~ aspect + dems + slopes + drds + nlcd + tricat + tpicat + (1|id), data = blvu1 )

summary(glmm1)

cat("
Ran at: ");Sys.time()
toc()
```

check fit of model

```{r}
tic()

#residuals
rglmm1<- residuals (glmm1, type = "pearson")
#qqplot of residuals
qqnorm (rglmm1)
qqline (rglmm1)
# predicted fit
fglmm1 <- fitted(glmm1)
#plot residuals vs predicted fit
plot(fglmm1,rglmm1)


cat("
Ran at: ");Sys.time()
toc()
```



```{r}
tic()

summary ()
cat("
Ran at: ");Sys.time()
toc()
```





```{r}
tic()

cat("
Ran at: ");Sys.time()
toc()
```



